added gradunwarping, bedpost grad dev correction, and scratch dir for probtrack connectivity

diff --git a/prepdwi b/prepdwi
--- a/prepdwi
+++ b/prepdwi
@@ -28,6 +28,9 @@ bedpost=1
 matching_T1w=
 n_cpus=8
 reg_init_subj=
+grad_coeff_file=
+scratch_dir=
+
 
 #default:
 atlas=dosenbach
@@ -42,19 +45,21 @@ if [ "$#" -lt 3 ]
 then
  echo "Usage: prepdwi bids_dir output_dir {participant,group,participant2} <optional arguments>"
  echo "          [--participant_label PARTICIPANT_LABEL [PARTICIPANT_LABEL...]]"
- echo "          [--matching_dwi MATCHING_PATTERN"
- echo "          [--matching_T1w MATCHING_STRING"
- echo "          [--reg_init_participant PARTICIPANT_LABEL"
+ echo "          [--matching_dwi MATCHING_PATTERN]"
+ echo "          [--matching_T1w MATCHING_STRING]"
+ echo "          [--reg_init_participant PARTICIPANT_LABEL]"
+ echo "          [--grad_coeff_file GRAD_COEFF_FILE]"
+ echo "          [-w WORK_DIR]  (scratch directory)"
  echo ""
  echo "          [--no-topup]"
  echo "          [--no-bedpost]"
  echo "          [--dke]"
- echo "          [--n_cpus] NCPUS (for bedpost, default: 8) "
+ echo "          [--n_cpus NCPUS] (for bedpost, default: 8) "
  echo ""
  echo " participant2 (probtrack connectivity) options:"
  echo "          [--nprobseeds] N (for probtrackx, default: 5000) "
  echo "      Choose built-in atlas:"
- echo "          {--atlas NAME (default: dosenbach)"
+ echo "          [--atlas NAME (default: dosenbach)"
  echo ""
  echo "       Available built-in atlas labels/csv:"
  pushd $execpath/cfg > /dev/null
@@ -101,7 +106,14 @@ while :; do
               die 'error: "--n_cpus" requires a non-empty option argument.'
             fi
               ;;
-
+     -w )       # takes an option argument; ensure it has been specified.
+          if [ "$2" ]; then
+                scratch_dir=$2
+                  shift
+	      else
+              die 'error: "-w" requires a non-empty option argument.'
+            fi
+              ;;
      --participant_label )       # takes an option argument; ensure it has been specified.
           if [ "$2" ]; then
                 participant_label=$2
@@ -161,6 +173,25 @@ while :; do
          die 'error: "--reg_init_participant" requires a non-empty option argument.'
           ;;
 
+
+       --grad_coeff_file )       # takes an option argument; ensure it has been specified.
+          if [ "$2" ]; then
+                grad_coeff_file=$2
+                  shift
+	      else
+              die 'error: "--grad_coeff_file" requires a non-empty option argument.'
+            fi
+              ;;
+     --grad_coeff_file=?*)
+          grad_coeff_file=${1#*=} # delete everything up to "=" and assign the remainder.
+            ;;
+          --grad_coeff_file=)         # handle the case of an empty --participant=
+         die 'error: "--grad_coeff_file" requires a non-empty option argument.'
+          ;;
+
+
+     
+      
       --atlas )       # takes an option argument; ensure it has been specified.
           if [ "$2" ]; then
                 atlas=$2
@@ -260,6 +291,28 @@ else
 	exit 1
 fi
 
+if [ -n "$grad_coeff_file" ]
+then
+        if [ -e $grad_coeff_file ]
+        then
+            grad_coeff_file=`realpath $grad_coeff_file`
+            final_suffix=regT1_gradCorr
+        do_gradcorr=1
+        else
+            echo "grad_coeff_file $grad_coeff_file does not exist! exiting!"
+            exit 1
+        fi
+
+else
+    final_suffix=regT1
+    do_gradcorr=0
+fi
+
+
+#exports for scripts to make use of
+export scratch_dir
+
+
 
 dwi_prefix=uncorrected
 
@@ -309,22 +362,25 @@ else
 fi
 
 
+
 #copy atlases to output folder, and run registration for all of them
 for atlas_dir in `ls -d $in_atlas_dir/*`
 do
  atlas_name=${atlas_dir##*/}
 
- iscopying=iscopying_${atlas_name}
- #mkdir to ensure only one process copies the files..
- if $(mkdir -p $iscopying )
+ if [ ! -e $atlas_name ]
  then
-   mkdir -p $atlas_name
+# iscopying=iscopying_${atlas_name}
+ #mkdir to ensure only one process copies the files..
+ if $(mkdir -p $atlas_name )
+ then
+ #  mkdir -p $atlas_name
    cp -Rv $atlas_dir/* $atlas_name
-   rmdir $iscopying
+ #  rmdir $iscopying
  else
    sleep 30 #wait for 1st job to finish copying
  fi
-
+ fi
 done
 
 
@@ -340,17 +396,23 @@ subj=`fixsubj $subj`
 N_t1w=`eval ls $in_bids/$subj/anat/${subj}${searchstring_t1w} | wc -l`
 in_t1w=`eval ls $in_bids/$subj/anat/${subj}${searchstring_t1w} | head -n 1`
 
-echo Found $N_t1w matching T1w, using first found: $in_t1w
 if [ ! -e $subj/t1/t1.nii.gz ]
 then
+echo --- Running importT1 ---
+echo Found $N_t1w matching T1w, using first found: $in_t1w
 echo $execpath/bin/importT1 $in_t1w $subj
 $execpath/bin/importT1 $in_t1w $subj
+else
+echo --- Skipping importT1 ---
 fi
 
 if [ ! -e $subj/${t1_img_type} ]
 then
+echo --- Running preprocT1 ---
 echo $execpath/bin/preprocT1 $subj
  $execpath/bin/preprocT1 $subj
+ else
+echo --- Skipping preprocT1 ---
 fi
 
 
@@ -386,37 +448,49 @@ then
 
 done #atlas_dir
 
+
 #only proceed with pre-processing if preproc dwi does not exist
-preproc_dwi=`ls $subj/dwi/uncorrected_*regT1/dwi.nii.gz | tail -n 1`
-if [ ! -e $preproc_dwi ]
-then
-
-
+#preproc_dwi=`ls $subj/dwi/uncorrected_*_${final_suffix}/dwi.nii.gz | tail -n 1`
+#echo returnval $?
+#echo before preproc
+#if [ ! -e $preproc_dwi ]
+#then
+#echo about to preproc
 
 Ndwi=`eval ls $in_bids/$subj/dwi/${subj}${searchstring_dwi} | wc -l`
 
  if [ ! -e $subj/dwi/uncorrected/dwi_$Ndwi.nii.gz ]
  then
-
+echo "--- Running importDWI ---"
  echo Ndwi=$Ndwi
 echo Found $Ndwi matching dwi, using all: 
  eval ls $in_bids/$subj/dwi/${subj}${searchstring_dwi}
 
  echo "$execpath/bin/importDWI ${dwi_prefix} $Ndwi `eval ls $in_bids/$subj/dwi/${subj}${searchstring_dwi}` $subj"
  $execpath/bin/importDWI ${dwi_prefix} $Ndwi `eval ls $in_bids/$subj/dwi/${subj}${searchstring_dwi}` $subj
+else
 
+echo "--- Skipping importDWI ---"
  fi
 
  if [ ! -e $subj/dwi/uncorrected_denoise/dwi_$Ndwi.nii.gz ]
  then
+echo "--- Running processDwiDenoise ---"
  echo $execpath/bin/processDwiDenoise uncorrected $subj
  $execpath/bin/processDwiDenoise uncorrected $subj
+ else
+
+echo "--- Skipping processDwiDenoise ---"
  fi
 
  if [ ! -e $subj/dwi/uncorrected_denoise_unring/dwi_$Ndwi.nii.gz ]
  then
+echo "--- Running processUnring ---"
  echo $execpath/bin/processUnring uncorrected_denoise $subj
  $execpath/bin/processUnring uncorrected_denoise $subj
+
+ else
+     echo "--- Skipping processUnring ---"
  fi
 
 
@@ -425,8 +499,11 @@ echo Found $Ndwi matching dwi, using all:
  
   if [ ! -e $subj/dwi/uncorrected_denoise_unring_eddy/dwi.nii.gz ]
   then
+echo "--- Running processEddyNoTopUp ---"
    echo $execpath/bin/processEddyNoTopUp uncorrected_denoise_unring $subj
    $execpath/bin/processEddyNoTopUp uncorrected_denoise_unring $subj
+   else
+echo "--- Skipping processEddyNoTopUp ---"
   fi
   
    eddy=eddy
@@ -434,25 +511,49 @@ echo Found $Ndwi matching dwi, using all:
 
   if [ ! -e $subj/dwi/uncorrected_denoise_unring_topup/dwi.nii.gz ]
   then 
+echo "--- Running processTopUp ---"
     echo $execpath/bin/processTopUp uncorrected_denoise_unring $subj
     $execpath/bin/processTopUp uncorrected_denoise_unring $subj
+else
+echo "--- Skipping processTopUp ---"
   fi
 
   if [ ! -e $subj/dwi/uncorrected_denoise_unring_topup_eddy/dwi.nii.gz ]
   then
+echo "--- Running processEddy ---"
     echo $execpath/bin/processEddy uncorrected_denoise_unring_topup $subj
     $execpath/bin/processEddy uncorrected_denoise_unring_topup $subj
+
+    else
+        echo "--- Skipping processEddy ---"
   fi
   eddy=topup_eddy
  fi
 
   if [ ! -e $subj/dwi/uncorrected_denoise_unring_${eddy}_regT1/dwi.nii.gz ]
   then
+echo "--- Running processRegT1 ---"
   echo $execpath/bin/processRegT1 uncorrected_denoise_unring_$eddy $subj
   $execpath/bin/processRegT1 uncorrected_denoise_unring_$eddy $subj
+else
+    echo "--- Skipping processRegT1 ---"
   fi
 
-  else
+  if [ $do_gradcorr = 1 ]
+  then
+   if [ ! -e $subj/dwi/uncorrected_denoise_unring_${eddy}_regT1_gradCorr/dwi.nii.gz ]
+   then
+echo "--- Running processGradUnwarp ---"
+  echo $execpath/bin/processGradUnwarp uncorrected_denoise_unring_$eddy $grad_coeff_file $subj
+  $execpath/bin/processGradUnwarp uncorrected_denoise_unring_$eddy $grad_coeff_file $subj
+  else 
+echo "--- Skipping processGradUnwarp ---"
+  fi
+  fi
+
+
+  #else #if preproc dwi exists
+
  #if exists already, just need to set eddy to the proper value
  if [ -e $subj/dwi/uncorrected_denoise_unring_eddy_regT1/dwi.nii.gz ]
  then
@@ -463,31 +564,61 @@ echo Found $Ndwi matching dwi, using all:
 	
 
   
-  fi #if not exist preproc dwi
+ # fi #if not exist preproc dwi
 
-  
+
+  #check if multi-shell
+  bval=$subj/dwi/uncorrected_denoise_unring_${eddy}_${final_suffix}/dwi.bval
+  shells=$subj/dwi/uncorrected_denoise_unring_${eddy}_${final_suffix}/dwi.shells
+ if [ ! -e $shells ]
+ then
+  echo "Checking number of shells..."
+  echo octave --path $execpath/octave --eval "writeShellsFromBval('$bval','$shells')"
+  octave --path $execpath/octave --eval "writeShellsFromBval('$bval','$shells')"
+ fi
+
+  nshells=`cat $shells | wc -l`
+  if [ "$nshells" -gt 1 ]
+  then
+      echo "--- Multi-shell DWI detected ---"
+       is_multishell=1
+       cat $shells
+   else
+      echo "--- Single-shell DWI detected ---"
+       is_multishell=0
+  fi
+
   #continue running pipelines
   if [ "$bedpost" = 1 ]
   then 
-    if [ ! -e $subj/dwi/uncorrected_denoise_unring_${eddy}_regT1/bedpost.bedpostX/dyads1.nii.gz ]
+    if [ ! -e $subj/dwi/uncorrected_denoise_unring_${eddy}_${final_suffix}/bedpost.bedpostX/dyads1.nii.gz ]
     then
-    echo $execpath/bin/processBedpost $n_cpus uncorrected_denoise_unring_${eddy}_regT1 $subj
-    $execpath/bin/processBedpost $n_cpus uncorrected_denoise_unring_${eddy}_regT1 $subj
+echo "--- Running processBedpost ---"
+    echo $execpath/bin/processBedpost $n_cpus uncorrected_denoise_unring_${eddy}_${final_suffix} $subj
+    $execpath/bin/processBedpost $n_cpus uncorrected_denoise_unring_${eddy}_${final_suffix} $subj
+    else
+        echo "--- Skipping processBedpost ---"
     fi
+    else
+        echo "--- Skipping processBedpost (--no-bedpost) ---"
   fi 
 
-  if [ "$dke" = 1 ]
+  if [ "$is_multishell" = 1 ]
   then 
-    if [ ! -e $subj/dwi/uncorrected_denoise_unring_${eddy}_regT1_dke/kmean.nii.gz ]
+    if [ ! -e $subj/dwi/uncorrected_denoise_unring_${eddy}_${final_suffix}_dke/kmean.nii.gz ]
     then
-    echo $execpath/bin/processDKE uncorrected_denoise_unring_${eddy}_regT1 $subj
-    $execpath/bin/processDKE uncorrected_denoise_unring_${eddy}_regT1 $subj
+echo "--- Running processDKE ---"
+    echo $execpath/bin/processDKE uncorrected_denoise_unring_${eddy}_${final_suffix} $subj
+    $execpath/bin/processDKE uncorrected_denoise_unring_${eddy}_${final_suffix} $subj
+    else
+        echo "--- Skipping processDKE ---"
     fi
   fi 
 
   #internally checks if files already exist before copying
-  echo $execpath/bin/processCleanupBIDS uncorrected_denoise_unring_${eddy}_regT1 $derivatives $subj
-  $execpath/bin/processCleanupBIDS uncorrected_denoise_unring_${eddy}_regT1 $derivatives $subj
+echo "--- Running processCleanupBIDS ---"
+  echo $execpath/bin/processCleanupBIDS uncorrected_denoise_unring_${eddy}_${final_suffix} $derivatives $subj
+  $execpath/bin/processCleanupBIDS uncorrected_denoise_unring_${eddy}_${final_suffix} $derivatives $subj
 
 done
 
@@ -499,6 +630,7 @@ elif [ "$analysis_level" = "group" ]
  then
 
     echo "generating preproc QC reports"
+    #TODO: move this to a separate script
 
     #need to make a subjlist for this command 
     for subj in $subjlist
@@ -519,6 +651,7 @@ elif [ "$analysis_level" = "group" ]
 
     #dwi and T1 reg
     $execpath/bin/genOverlay_mask  dwi/uncorrected_*_regT1/dwi.nii.gz dwi/uncorrected_*_regT1/epi_reg/t1_diffres.nii.gz reg_dwi_t1 $subj > /dev/null
+    
 
     popd
    
