added in_brainmask_dir option, to override brainmask and re-run t1w registration (NOTE: still does not employ t1w brainmask for DWI)

diff --git a/prepdwi b/prepdwi
--- a/prepdwi
+++ b/prepdwi
@@ -30,6 +30,9 @@ sess=$1
 execpath=`dirname $0`
 execpath=`realpath $execpath`
 
+in_brainmask_dir=
+
+
 in_atlas_dir=$execpath/atlases
 
 matching_dwi=
@@ -77,6 +80,7 @@ then
  echo "          [--matching_dwi MATCHING_PATTERN] (for selecting dwi)"
  echo "          [--matching_T1w MATCHING_STRING] (for selecting T1w)"
  echo""
+ echo "		 [--in_brainmask_dir BRAINMASK_DIR]  (e.g. output root folder from gradcorrected 7TBEaST)"
  echo "          [--reg_init_participant sub-SUBJ --OR-- sub-SUBJ_ses-SES]"
  echo ""
  echo "          [--no-denoise]"
@@ -256,6 +260,21 @@ while :; do
             ;;
           --resample_res=)         # handle the case of an empty --participant=
          die 'error: "--resample_res" requires a non-empty option argument.'
+          ;;
+
+      --in_brainmask_dir )       # takes an option argument; ensure it has been specified.
+          if [ "$2" ]; then
+                in_brainmask_dir=$2
+                  shift
+	      else
+              die 'error: "--in_brainmask_dir" requires a non-empty option argument.'
+            fi
+              ;;
+     --in_brainmask_dir=?*)
+          in_brainmask_dir=${1#*=} # delete everything up to "=" and assign the remainder.
+            ;;
+          --in_brainmask_dir=)         # handle the case of an empty --participant=
+         die 'error: "--in_brainmask_dir" requires a non-empty option argument.'
           ;;
 
 
@@ -466,6 +485,22 @@ else
 fi
 
 
+if [ -n "$in_brainmask_dir" ]
+then
+
+ if [ ! -e $in_brainmask_dir ]
+ then
+    echo "Input brainmask dir $in_brainmask_dir does not exist! exiting.."
+    exit 1
+ fi
+
+ custom_brainmask=1
+ searchstring_brainmask=*T1w*brain.nii.gz #skull-stripped intensity normalized T1w
+
+else
+ custom_brainmask=0
+
+fi
 
 t1_img_type=t1/t1.brain.inorm.nii.gz
 
@@ -500,16 +535,39 @@ do
 #========================================================================
 #========================================================================
 
+
+
+if [ "$custom_brainmask" = 1 ]
+then
+
+t1w_in_brainmask=`eval ls $in_brainmask_dir/$subj_sess_dir/anat/${subj_sess_prefix}${searchstring_brainmask} | head -n 1`
+
+if [ -e $t1w_in_brainmask ]
+then
+	echo "Using pre-computed skull-stripped image..."
+	echo cp -v $t1w_in_brainmask $subj_sess_prefix/t1/t1.brain.inorm.nii.gz
+	cp -v $t1w_in_brainmask $subj_sess_prefix/t1/t1.brain.inorm.nii.gz
+fi
+
+fi
+
+
 N_t1w=`eval ls $in_bids/$subj_sess_dir/anat/${subj_sess_prefix}${searchstring_t1w} | wc -l`
 in_t1w=`eval ls $in_bids/$subj_sess_dir/anat/${subj_sess_prefix}${searchstring_t1w} | head -n 1`
 
 if [ "$N_t1w" = 0 ]
 then
 	
-	echo "--- No T1w images found! ---"
+	echo "--- No T1w images found in $in_bids/$subj_sess_dir/anat ---"
+
+	if [ "$custom_brainmask" = 0 ]
+	then
 	echo "	automatically setting --no-regT1"
-	noregT1=1
+		noregT1=1
+	fi
 fi
+
+
 
 if [ "$noregT1" = 1 ]
 then
@@ -519,25 +577,24 @@ else
 
 if [ ! -e $subj_sess_prefix/t1/t1.nii.gz ]
 then
-echo --- Running importT1 ---
-echo Found $N_t1w matching T1w, using first found: $in_t1w
-echo $execpath/bin/importT1 $in_t1w $subj_sess_prefix
-$execpath/bin/importT1 $in_t1w $subj_sess_prefix
+ echo --- Running importT1 ---
+ echo Found $N_t1w matching T1w, using first found: $in_t1w
+ echo $execpath/bin/importT1 $in_t1w $subj_sess_prefix
+ $execpath/bin/importT1 $in_t1w $subj_sess_prefix
 else
-echo --- Skipping importT1 ---
+ echo --- Skipping importT1 ---
 fi
 
 
-
-if [ ! -e $subj_sess_prefix/${t1_img_type} ]
+#preprocess T1w internally
+if [ ! -e $subj_sess_prefix/${t1_img_type} ] &&  [ "$custom_brainmask" = 0 ]
 then
 echo --- Running preprocT1 ---
-echo $execpath/bin/preprocT1 $subj_sess_prefix
- $execpath/bin/preprocT1 $subj_sess_prefix
+	echo $execpath/bin/preprocT1 $subj_sess_prefix
+	 $execpath/bin/preprocT1 $subj_sess_prefix
  else
-echo --- Skipping preprocT1 ---
+	echo --- Skipping preprocT1 ---
 fi
-
 
 #register t1 to atlases
 for atlas_dir in `ls -d $in_atlas_dir/*`
@@ -545,10 +602,13 @@ do
  atlas_name=${atlas_dir##*/}
 
 
-#TODO: need to convert reg_init_subj to subj_sess
 
 if [ -n "$reg_init_subj" ]
 then
+
+ #add on sub- prefix if it doesn't exist
+ reg_init_subj=`fixsubj $reg_init_subj`
+
  echo --- Running atlas affine registration initialized with $reg_init_subj xfm ---
  echo $execpath/bin/reg_intersubj_aladin  t1 $t1_img_type $atlas_name $subj_sess_prefix -i $reg_init_subj
  $execpath/bin/reg_intersubj_aladin  t1 $t1_img_type $atlas_name $subj_sess_prefix -i $reg_init_subj
@@ -558,7 +618,7 @@ then
 
  else
      
- if [ ! -e $subj_sess_prefix/reg/affine_aladin_t1/${atlas_name}_$subj_sess_prefix/${atlas_name}_to_${subj_sess_prefix}.xfm ]
+ if [ ! -e $subj_sess_prefix/reg/affine_aladin_t1/${atlas_name}_$subj_sess_prefix/${atlas_name}_to_${subj_sess_prefix}.xfm ] || [ "$custom_brainmask" = 1 ]
  then
  echo --- Running atlas affine registration ---
  echo $execpath/bin/reg_intersubj_aladin  t1 $t1_img_type $atlas_name $subj_sess_prefix 
@@ -567,7 +627,7 @@ then
  echo --- Skipping atlas affine registration ---
  fi
 
- if [ ! -e $subj_sess_prefix/reg/bspline_f3d_t1/${atlas_name}_$subj_sess_prefix/ctrlpt_${atlas_name}_to_${subj_sess_prefix}.nii.gz ]
+ if [ ! -e $subj_sess_prefix/reg/bspline_f3d_t1/${atlas_name}_$subj_sess_prefix/ctrlpt_${atlas_name}_to_${subj_sess_prefix}.nii.gz ] || [ "$custom_brainmask" = 1 ]
  then
     echo --- Running atlas b-spline registration ---
     echo $execpath/bin/reg_bspline_f3d t1 $t1_img_type $atlas_name $subj_sess_prefix
